# File: .github/dependabot.yml

version: 2
updates:

  # 1. GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"  # Location of .github/workflows/
    schedule:
      interval: "daily"

  # 2. Python dependencies (requirements.txt)
  - package-ecosystem: "pip"
    directory: "/"  # Path to requirements.txt
    schedule:
      interval: "daily"

  # 3. Dockerfile base image
  - package-ecosystem: "docker"
    directory: "/"  # Path to Dockerfile
    schedule:
      interval: "daily"

  # 4. JavaScript/Node.js (package.json and package-lock.json)
  - package-ecosystem: "npm"
    directory: "/"  # Path to package.json
    schedule:
      interval: "daily"
