# .github/workflows/publish.yml
name: Push Docker image to GHCR

on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v3

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN }}

    - name: Build and Push
      run: |
        docker build -t ghcr.io/vignesh2122/my-app:latest .
        docker push ghcr.io/vignesh2122/my-app:latest

