name: Full Deploy Workflow
on:
  workflow_dispatch:
    inputs:
      db_action:
        description: "Database action"
        required: true
        default: "no"
        type: choice
        options:
          - "yes"
          - "no"

      s3_flush:
        description: "Flush S3 bucket?"
        required: true
        default: "no"
        type: choice
        options:
          - "yes"
          - "no"

      cognito_flush:
        description: "Delete Cognito users?"
        required: true
        default: "no"
        type: choice
        options:
          - "yes"
          - "no"

env:
  AWS_REGION: ap-south-1
  INSTANCE_ID: i-0e7eb8aab2e6b34b1
  SSM_DOCUMENT_NAME: deployment
  ECR_REGISTRY: 674845781849.dkr.ecr.ap-south-1.amazonaws.com
  ECR_REPOSITORY: demo

permissions:
  id-token: write
  contents: read

jobs:
  flush-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::674845781849:role/github
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Docker Image
        env:
          IMAGE_TAG: ${{ github.run_number }}
        run: |
          echo "🔨 Building Docker image: $IMAGE_TAG"
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Trigger SSM Document with Selected Options
        run: |
          echo "🚀 Triggering SSM document with:"
          echo " - DB Action: ${{ github.event.inputs.db_action }}"
          echo " - S3 Flush:  ${{ github.event.inputs.s3_flush }}"
          echo " - Cognito Flush: ${{ github.event.inputs.cognito_flush }}"

          aws ssm send-command \
            --document-name "$SSM_DOCUMENT_NAME" \
            --targets "Key=InstanceIds,Values=${{ env.INSTANCE_ID }}" \
            --region "${{ env.AWS_REGION }}" \
            --parameters "dbAction=${{ github.event.inputs.db_action }},s3Action=${{ github.event.inputs.s3_flush }},cognitoAction=${{ github.event.inputs.cognito_flush }}" \
            --comment "Deploy with inputs from GitHub Actions"
