name: Full Deploy Workflow

on:
  workflow_dispatch:
    inputs:
      db_action:
        description: "Database action"
        required: true
        default: "UPDATE"
        type: choice
        options:
          - "CREATE"
          - "UPDATE"

      s3_flush:
        description: "Flush S3 bucket?"
        required: true
        default: "no"
        type: choice
        options:
          - "yes"
          - "no"

      cognito_flush:
        description: "Delete Cognito users?"
        required: true
        default: "no"
        type: choice
        options:
          - "yes"
          - "no"

      development:
        description: "Choose development environment"
        required: true
        default: "dev"
        type: choice
        options:
          - "dev"
          - "test"

env:
  AWS_REGION: ap-south-1
  INSTANCE_ID: i-0e7eb8aab2e6b34b1
  SSM_DOCUMENT_NAME: Full-Deploy-Document
  Dev_ECR_REGISTRY: 674845781849.dkr.ecr.ap-south-1.amazonaws.com
  UAT_ECR_REGISTRY: 674845781849.dkr.ecr.ap-south-1.amazonaws.com
  Dev_REPOSITORY: demo-dev
  Test_REPOSITORY: demo-test
  IMAGE_NAME: demo-image

permissions:
  id-token: write
  contents: read
  issues: write   

jobs:
  flush-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Wait for manual approval before starting build
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.TOKEN }}
          approvers:  Vignesh2122 , GokulJ17
          minimum-approvals: 1
          issue-title: "🚨 Approval Required: Deploy v${{ github.run_number }} to ${{ github.event.inputs.development }}"
          issue-body: |
            Please approve or deny the deployment:
            - Environment: ${{ github.event.inputs.development }}
            - DB Action: ${{ github.event.inputs.db_action }}
            - S3 Flush:  ${{ github.event.inputs.s3_flush }}
            - Cognito Flush: ${{ github.event.inputs.cognito_flush }}
          fail-on-denial: true
          exclude-workflow-initiator-as-approver: false

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::674845781849:role/github
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Docker Image
        env:
          IMAGE_TAG: ${{ github.run_number }}
        run: |
          echo "🔨 Building Docker image with tag: $IMAGE_TAG"

          if [ "${{ github.event.inputs.development }}" == "dev" ]; then
            ECR_REPOSITORY=${{ env.Dev_REPOSITORY }}
            ECR_REGISTRY=${{ env.Dev_ECR_REGISTRY }}
            echo "Using DEV ECR: $ECR_REGISTRY/$ECR_REPOSITORY"
          else
            ECR_REPOSITORY=${{ env.Test_REPOSITORY }}
            ECR_REGISTRY=${{ env.UAT_ECR_REGISTRY }}
            echo "Using TEST ECR: $ECR_REGISTRY/$ECR_REPOSITORY"
          fi

          docker build -t ${{ env.IMAGE_NAME }}:$IMAGE_TAG .
          docker tag ${{ env.IMAGE_NAME }}:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Trigger SSM Document with Selected Options
        run: |
          echo "🚀 Triggering SSM document with:"
          echo " - DB Action: ${{ github.event.inputs.db_action }}"
          echo " - S3 Flush:  ${{ github.event.inputs.s3_flush }}"
          echo " - Cognito Flush: ${{ github.event.inputs.cognito_flush }}"
          echo " - Environment: ${{ github.event.inputs.development }}"

          aws ssm send-command \
            --document-name "$SSM_DOCUMENT_NAME" \
            --targets "Key=InstanceIds,Values=${{ env.INSTANCE_ID }}" \
            --region "${{ env.AWS_REGION }}" \
            --parameters "development=${{ github.event.inputs.development}},dbAction=${{ github.event.inputs.db_action}},s3Action=${{ github.event.inputs.s3_flush}},cognitoAction=${{ github.event.inputs.cognito_flush}}" \
            --comment "Deploy triggered by GitHub Actions"
