name: Build and Push Docker Image to ECR

on:
  workflow_dispatch:
    inputs:
      db_action:
        description: "Select database operation"
        required: true
        default: "UPDATE"
        type: choice
        options:
          - CREATE
          - UPDATE

env:
  AWS_REGION: ap-south-1
  ECR_REGISTRY: 674845781849.dkr.ecr.ap-south-1.amazonaws.com
  ECR_REPOSITORY: demo

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::674845781849:oidc-provider/token.actions.githubusercontent.com
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push Docker image
        env:
          IMAGE_TAG: ${{ github.run_number }}
        run: |
          echo "Building image with tag: $IMAGE_TAG"
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Trigger SSM Document based on DB Action
        env:
          AWS_REGION: ap-south-1
          SSM_INSTANCE_ID: i-09323899115ace7fa
        run: |
          if [ "${{ github.event.inputs.db_action }}" == "CREATE" ]; then
            DOC_NAME="db-change"
          else
            DOC_NAME="Docker-compose"
          fi

          echo "Running SSM document: $DOC_NAME"

          aws ssm send-command \
            --document-name "$DOC_NAME" \
            --targets "Key=InstanceIds,Values=$SSM_INSTANCE_ID" \
            --region "$AWS_REGION"
